/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 grandpiano.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model({ materials, props }) {
  const { nodes } = useGLTF('/grandpiano.glb')

  console.log(props)
  return (
    <group castShadow dispose={null}>
      <mesh castShadow geometry={nodes.Cube001.geometry} material={materials.whiteKeyMaterial} />
      <mesh castShadow geometry={nodes.Cube002.geometry} material={materials.whiteKeyMaterial} />
      <mesh castShadow geometry={nodes.blackkey.geometry} material={materials.blackKeyMaterial} />
      <mesh castShadow geometry={nodes.blackkey001.geometry} material={materials.blackKeyMaterial} />
      <mesh castShadow geometry={nodes.blackkey002.geometry} material={materials.blackKeyMaterial} />
      <mesh castShadow geometry={nodes.blackkey003.geometry} material={materials.blackKeyMaterial} />
      <mesh castShadow geometry={nodes.blackkey004.geometry} material={materials.blackKeyMaterial} />
      <mesh castShadow geometry={nodes.blackkey005.geometry} material={materials.blackKeyMaterial} />
      <mesh castShadow geometry={nodes.blackkey006.geometry} material={materials.blackKeyMaterial} />
      <mesh castShadow geometry={nodes.blackkey007.geometry} material={materials.blackKeyMaterial} />
      <mesh castShadow geometry={nodes.Cube004.geometry} material={materials.whiteKeyMaterial} />
      <mesh castShadow geometry={nodes.White_Keys01.geometry} material={materials.whiteKeyMaterial} />
      <mesh castShadow geometry={nodes.White_Keys002.geometry} material={materials.whiteKeyMaterial} />
      <mesh castShadow geometry={nodes.White_Keys003.geometry} material={materials.whiteKeyMaterial} />
      <mesh castShadow geometry={nodes.White_Keys004.geometry} material={materials.whiteKeyMaterial} />
      <mesh castShadow geometry={nodes.White_Keys005.geometry} material={materials.whiteKeyMaterial} />
      <mesh castShadow geometry={nodes.White_Keys006.geometry} material={materials.whiteKeyMaterial} />
      <mesh castShadow geometry={nodes.White_Keys007.geometry} material={materials.whiteKeyMaterial} />
      <mesh castShadow geometry={nodes.White_Keys008.geometry} material={materials.whiteKeyMaterial} />
    </group>
  )
}

useGLTF.preload('/grandpiano.glb')
