/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 grandpiano.glb
*/

import React, { useRef } from 'react'
import { Html, useGLTF } from '@react-three/drei'
import Tablet from './Tablet'

export function Model({ materials, toTablet }) {
  const { nodes } = useGLTF('/grandpiano.glb')

  const ref = useRef();
  console.log(ref)

  return (
    <group dispose={null}>
      <mesh castShadow geometry={nodes.Main.geometry} material={materials.whiteKeyMaterial} />
      <mesh castShadow geometry={nodes.blackkey.geometry} material={materials.blackKeyMaterial} />
      <mesh castShadow geometry={nodes.blackkey001.geometry} material={materials.blackKeyMaterial} />
      <mesh castShadow geometry={nodes.blackkey002.geometry} material={materials.blackKeyMaterial} />
      <mesh castShadow geometry={nodes.blackkey003.geometry} material={materials.blackKeyMaterial} />
      <mesh castShadow geometry={nodes.blackkey004.geometry} material={materials.blackKeyMaterial} />
      <mesh castShadow geometry={nodes.blackkey005.geometry} material={materials.blackKeyMaterial} />
      <mesh castShadow geometry={nodes.blackkey006.geometry} material={materials.blackKeyMaterial} />
      <mesh castShadow geometry={nodes.blackkey007.geometry} material={materials.blackKeyMaterial} />
      <mesh castShadow geometry={nodes.White_Keys01.geometry} material={materials.whiteKeyMaterial} />
      <mesh castShadow geometry={nodes.White_Keys002.geometry} material={materials.whiteKeyMaterial} />
      <mesh castShadow geometry={nodes.White_Keys003.geometry} material={materials.whiteKeyMaterial} />
      <mesh castShadow geometry={nodes.White_Keys004.geometry} material={materials.whiteKeyMaterial} />
      <mesh castShadow geometry={nodes.White_Keys005.geometry} material={materials.whiteKeyMaterial} />
      <mesh castShadow geometry={nodes.White_Keys006.geometry} material={materials.whiteKeyMaterial} />
      <mesh castShadow geometry={nodes.White_Keys007.geometry} material={materials.whiteKeyMaterial} />
      <mesh castShadow geometry={nodes.White_Keys008.geometry} material={materials.whiteKeyMaterial} />
      <mesh castShadow geometry={nodes.FrontBrassPiece.geometry} material={materials.brassMaterial} position={[0.05, 1.56, 0.6]} />
      <mesh castShadow geometry={nodes.BackBrassPiece.geometry} material={materials.brassMaterial} />
      <mesh castShadow geometry={nodes.BrassBridges.geometry} material={materials.brassMaterial} />
      <mesh castShadow geometry={nodes.Wires01.geometry} material={nodes.Wires01.material} position={[-0.56, 1.55, -0.13]} />
      <mesh castShadow geometry={nodes.Wires02.geometry} material={nodes.Wires02.material} position={[0.06, 1.54, 0.28]} />
      <mesh castShadow geometry={nodes.Pegs.geometry} material={materials.redMaterial} position={[0.15, 1.53, -0.12]} />
      <mesh castShadow geometry={nodes.RedBar.geometry} material={materials.redMaterial} position={[0.05, 1.53, 0.54]} />
      <mesh castShadow geometry={nodes.WoodBase.geometry} material={materials.woodMaterial} />
      <mesh castShadow geometry={nodes.Pegs02.geometry} material={materials.redMaterial} />
      <mesh castShadow geometry={nodes.Wires03.geometry} material={nodes.Wires03.material} />
      <mesh ref={ref} onClick={(e) => console.log(e)} castShadow geometry={nodes.Cube.geometry} material={materials.blackKeyMaterial}>
        <Tablet toTablet={toTablet} />
      </mesh>
      <mesh castShadow geometry={nodes.Logo.geometry} material={materials.redMaterial} position={[-0.18, 1.53, 1.005]} rotation={[Math.PI / 2, 0, 0]} scale={0.1} />
    </group>
  )
}

useGLTF.preload('/grandpiano.glb')
